# This is a basic workflow to help you get started with Actions

name: XML2JSON #Change the Name

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      # name: Use Github App
      - uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      # name: Data Format Converter Action
      - uses: fabasoad/data-format-converter-action@main
        id: xml2json
        with:
          input: "person.xml"
          from: "xml"
          to: "json"
          token: ${{ steps.generate-app-token.outputs.token }}
      - name: Print result
        run: echo  '${{ steps.xml2json.outputs.output }}' > result.json
      - run: cat result.json
  save-output:
    - name: Run a command and save output to a file
      run: |
        cat result.json

    - name: Configure Git
      run: |
        git config --global user.name 'adamdjbrett'
        git config --global user.email '22662978+adamdjbrett@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add result.json
        git commit -m "Save output to file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        